// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Threading;


using UnityEngine;

namespace taskDependentSupport.core
{
		public class Counter
		{
				
				private int value;

				public Counter ()
				{
				}

				public void resetCounter()
				{
					value = 0;
				}

				public int getValue()
				{
					return value;
				}

				public void increaseCounter(){
					while (true) {
						Thread.Sleep (10);
						value += 1;
					}
				}
			
		}
}

